# Site settings
title: bluss' rust bursts
email: 
description: ""
baseurl: "https://bluss.github.io/"
url: ""
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
